import type { BriefData } from '@/lib/brief-data';

const data: BriefData = {
  escalation: {
    direction: 'escalating',
    risk7d: 'extreme',
    spillover: 'critical',
    rationale: {
      direction:
        "Direction holds escalating on Day 192 as Iran answered Washington's 'small potatoes' framing not with restraint but with a doctrinal escalation. Parliament speaker and lead negotiator Mohammad Bagher Ghalibaf declared on Sunday that Tehran's 'proportionate responses' are over, that further US attacks would draw a 'faster, heavier and more painful' blow, and that the United States should grasp the 'rules of the game have changed before it is too late.' The threat sat atop real military escalation: analysts read Iran's first use of anti-ship ballistic missiles — fired from Isfahan and Kerman at a US carrier and destroyer on Friday, both evaded per CENTCOM — and the US strike on three Iranian tankers near Kharg as a two-way 'tanker war' now settling onto the strait. Per §3.5.3 the Iranian escalation-dominance claim runs alongside Ghalibaf's own admission of 'fundamental challenges' — inflation, unemployment, a sliding rial — the mirror image of Trump minimizing the war's scale while the market prices it up. Nothing on Day 192 reversed the return to force.",
      risk7d:
        "Seven-day risk holds extreme. Iran has now publicly retired the proportionality cap that governed its earlier retaliation and debuted anti-ship ballistic missiles against US warships, raising both the ceiling and the tempo of what a single further US strike could trigger. The near-term tails stay loaded and are now more likely to fire: a laden-tanker loss in a mined, contested strait where four-to-six vessels a day transit AIS-dark; a lost escort convoy; a US casualty from an anti-ship salvo that an evasion does not dodge next time; a strike on a Gulf host; or a named major-Chinese-bank designation. Brent, having just booked its biggest weekly gain of the war to a six-week high near $96, sits closer to the >$100 trigger on a drawn-down stock base. The narrative front adds its own tail — two principals now performing for domestic audiences, Trump shrinking the war's name while Ghalibaf inflates the threat — but the tape, the tanker war and the interceptor tempo all point the same way.",
      spillover:
        "Spillover holds critical and edged toward worsening. Israel executed its threatened Lebanon reprisal, killing at least three and wounding 23 after a Hezbollah drone launch — a June-ceasefire violation and a fresh confirmed death in a connected theater the series does not fold into the war cumulative. The map stays wide: Iranian soil under a continuing campaign, both maritime chokepoints, the Gulf host states directly targeted across the recent cycle, the Israel-Gaza and Israel-Lebanon seams, an open Houthi front bearing on the Yanbu pipeline workaround, and a formalized economic front wired to the September 24 US-China summit. Per §3.5.5 the reach still outran the damage on the Iran front — the carrier and destroyer evaded the anti-ship salvo with no casualty — but the collapse of Hormuz throughput to about a fifth of pre-war flow, China's open defiance, and the deepening execution wave (78-92 documented in August) are the standing worsening signals.",
    },
  },
  events: [
    {
      id: 1,
      direction: 'pivotal',
      importance: 'pivotal',
      source: 'CNBC / Irish Times / IRNA (via GlobalSecurity)',
      event:
        "Iran retired its proportionality cap: parliament speaker and lead negotiator Mohammad Bagher Ghalibaf declared on Sunday that Tehran's 'proportionate responses' to US attacks are over, that further strikes would be met 'faster, heavier and more painful,' and that Washington should understand the 'rules of the game have changed before it is too late' — while acknowledging Iran faces 'fundamental challenges' of inflation, unemployment and exchange-rate volatility.",
      summary:
        "Per §3.5.3 this is Tehran's answer to 'small potatoes' — an escalation-dominance claim from the regime's chief negotiator, paired in the same statement with a rare admission that the economic war is biting; the two principals now mirror each other, one shrinking the war's name, the other inflating the threat.",
      impact:
        "The political-will and negotiation-capacity clocks move: an Iran that publicly abandons proportionality and debuts anti-ship missiles raises the ceiling on the next exchange, while the economic-strain admission signals the sanctions track is landing even as the diplomatic track stays closed.",
    },
    {
      id: 2,
      direction: 'escalating',
      importance: 'high',
      source: 'Al Jazeera / CNN / PBS / Euronews',
      event:
        "The war settled into a 'tanker war' at sea: Iran fired anti-ship ballistic missiles from Isfahan and Kerman at a US carrier and destroyer near the Strait of Hormuz on Friday — read by analysts as its first such use and a 'calculated escalation' — which CENTCOM said the ships 'successfully evaded' with no personnel hurt, after which the US struck three Iranian oil tankers near Kharg Island and Tehran claimed hits on US-linked vessels.",
      summary:
        "Per §3.5.5 the fight has moved a rung up the ladder — from Iranian mine-laying and US airstrikes to a two-way naval missile exchange over the chokepoint — with Kpler-tracked transits at four-to-six vessels a day (many AIS-dark) against a pre-war 100-120 and Hormuz throughput near a fifth of normal.",
      impact:
        "The energy-infrastructure and interceptor-reconstitution clocks move: anti-ship ballistic missiles against a carrier group are a qualitatively higher threat than mines, and one salvo the ships do not evade is both a mass-casualty event and a >$100 Brent trigger.",
    },
    {
      id: 3,
      direction: 'escalating',
      importance: 'high',
      source: 'Trading Economics / Al Jazeera / Windward / Fortune',
      event:
        "The market and the maritime data kept pricing the war as consequential: Brent held near $96 after its biggest weekly gain of the war (roughly 8-9%), independent tracking put Hormuz throughput near a fifth of pre-war flow against Washington's higher claims, war-risk insurance sat multiples above normal, and China — which buys the bulk of Iran's oil — stayed defiant, its ministry vowing to 'take all necessary measures' as the threatened major-Chinese-bank designation kept slipping behind the September 24 summit.",
      summary:
        "Per §3.5.3 and §3.5.5 the gap between framing and record widened on both ends: 'small potatoes' against an 8-9% weekly oil move and a fifth-of-normal chokepoint, and 'cut off from the dollar' against a bank blow Beijing openly dares Washington to deliver.",
      impact:
        "The energy-infrastructure clock stays dominant and the rupture tail loaded: a laden-tanker loss, a lost escort convoy, or a named Chinese bank sends Brent past $100 in a session, with the dual-closure $150-200 tail one sinking away.",
    },
    {
      id: 4,
      direction: 'mixed',
      importance: 'medium',
      source: 'Times of Israel / HRANA / Iran HRM / Jordan News',
      event:
        "The connected fronts hardened: Israel executed its threatened Lebanon reprisal, killing at least three and wounding 23 in strikes on five southern and Beqaa locations after a Hezbollah drone launch it called a June-ceasefire violation; Iran's postwar execution wave surged, with HRANA documenting 78 executions in August (Iran HRM 92, most carried out secretly) and ten Isfahan protesters newly sentenced to death; the IAEA said inspections would come 'soon' but remained short of verified access; and Gaza stayed deadlocked on disarmament.",
      summary:
        "Per §3.5.6 the standing priors hold unresolved — the Israeli-independence and Lebanon-gap priors (Israel acting on its own clock), the unverified nuclear file, the Gaza sequencing deadlock — and per §3.1 the worsening rights thread stays out of the war toll.",
      impact:
        "The humanitarian-escalation and coalition-cohesion clocks move: the war widens on the Lebanon, nuclear, Gaza and human-rights vectors even on a day whose center of gravity was the US-Iran naval and narrative fight.",
    },
  ],
  casualties: {
    us: {
      cumulative:
        'KIA: 17 confirmed · WIA: 432 (AP/CENTCOM combat series; ~96% returned to duty). DoD DCAS all-cause series holds 18 killed · 687 wounded.',
      delta:
        "+0 confirmed on the AP/CENTCOM combat series into Day 192 — a fifth day with no verified new US combat casualty. CENTCOM said a carrier and destroyer 'successfully evaded' Iran's Friday anti-ship ballistic-missile salvo near Hormuz with no personnel hurt, but Ghalibaf's 'faster, heavier and more painful' declaration and the debut of anti-ship missiles raise the odds the next salvo lands. Per §3.5.3 the 18th DCAS death stays unconfirmed as hostile, Trump's 'per ship' rule is not triggered, and Iran's earlier claim of American service members killed stays denied and uncounted. The escort convoy (~8-9 mb/d) runs amid live fire with the USS George Washington on station; the blockade holds at eighty-six vessels rerouted, three disabled, two boarded.",
      status:
        "The headline holds at 17 KIA / 432 WIA on the AP/CENTCOM combat series against the wider DoD DCAS all-cause tally of 18 killed / 687 wounded since February 28. Per §3.5.3 keep the combat figure and flag DCAS; the divergence is now a rhetorical fact carried from Day 191, when the President reached for the '18' while calling the war 'small potatoes.' Day 192 added no US count — a fifth quiet day — but the exposure rose in kind, not degree: Iran's first anti-ship ballistic missiles against a carrier group, evaded on Friday, are a qualitatively higher threat than mines, and Ghalibaf's public retirement of the proportionality cap signals the next Iranian answer to a US strike is meant to be larger. The escort convoy (~660 million barrels and ~1,300 vessels since May, moving ~8-9 mb/d) runs amid live fire; CENTCOM's blockade holds at roughly eighty-six vessels rerouted; and the IRGC navy's 'unauthorized routes' warning keeps a single unevaded salvo one event away from Trump's reprisal rule. The $67 billion supplemental and the 50-48 Senate war-powers rebuke stay unresolved in recess ahead of the November midterms.",
    },
    israel: {
      cumulative: 'KIA: 56 (Iran-front 47 + Lebanon-front 9) · WIA: 8,652+',
      delta:
        "+0 on the Iran front and no new Israeli military fatalities on the Lebanon front — the Hezbollah drone was shot down and no soldiers were hurt, per the IDF. Israel stayed offstage on the US-Iran naval and narrative fight while executing its threatened Lebanon reprisal (the Lebanese dead are logged under 'other') and holding its Gaza campaign deadlocked and lethal — a connected theater, not folded into the war cumulative.",
      status:
        "Israeli casualties hold at 56 KIA / 8,652+ WIA on the Iran front; no new Israeli toll on Day 192. Israel's own fronts stayed hot: late Friday the IDF struck five locations across southern Lebanon and the Beqaa after a Hezbollah drone launch it called a 'blatant violation' of the June ceasefire, killing at least three and wounding 23 (logged under 'other'), the threatened reprisal now executed. On Gaza the US-led Board of Peace insists no Israeli withdrawal before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap — 1,100-1,200+ Palestinians killed since the October 2025 ceasefire, at least 36 since the disarmament deal, a connected theater the series does not fold into the war cumulative. Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold — Israel acts on its own clock, outside the US-Iran framework.",
    },
    iran: {
      cumulative:
        'Foundation of Martyrs ~3,468 KIA · HRANA 3,636+ documented (1,221 mil / 1,701 civ / 714 unclassified) · MOH ~3,559 killed / 27,400+ wounded · US-Israeli est. 6,000+ · 3.2M displaced',
      delta:
        "No update to the official war toll; Day 192's tanker exchange produced no released Iranian count. The rights thread deepened on the monthly data: HRANA documented 78 executions across Iran in August (including five women and two hangings tied to the January 2026 protests), while Iran HRM put the August total at 92, most carried out secretly, with ten Isfahan protesters newly sentenced to death — a thread kept out of the war toll per §3.1. The contested September 1 Kuhestak wedding strike carries per §3.1 dual-sourcing (NYT-corroborated US bomb; Iranian-source toll of up to five killed and 68+ wounded held pending verification).",
      status:
        "The official Iranian war toll carries pending an update; Day 192 added no new war-front count from the naval exchange. The movement was on the rights thread, kept out of the war cumulative per §3.1: HRANA's August monthly report documented 78 executions (five women; two men hanged over the January 2026 protests) and Iran HRM put the month at 92 — most carried out in secret — with ten defendants in an Isfahan protest case newly sentenced to death, and Amnesty warning many more protesters are at risk since the February 28 attacks. The contested civilian figure holds: the September 1 Kuhestak wedding strike is independently corroborated as a US-released bomb, but the toll of up to five killed (reportedly including children aged four and sixteen) and 68+ wounded remains an Iranian-source count held pending verification and not folded into the MOH aggregate; September 1 military casualties (sixteen minelayers, IRGC coastal sites) remain unreleased. Cumulative HRANA stands at 3,636+ with its understatement caveat, Foundation of Martyrs ~3,468, MOH ~3,559 / 27,400+, US and Israeli estimates to 6,000+. The IAEA said inspections would come 'soon' and modalities were being defined, but inspectors stay denied access to the bombed sites; the ~440.9 kg of 60% HEU plus ~184.1 kg of 20% stays unverified and likely at Isfahan, ISIS flagging enough for up to ten weapons if further enriched.",
    },
    other: {
      cumulative:
        "Lebanon source-split: Health Ministry ~4,265 / 12,190+ vs Wikipedia 3,371 / 10,129 · Iraq 148+ KIA / 402+ WIA · Gulf 33+ KIA / 85+ WIA (Kuwait 10 killed / 115 injured; Saudi Arabia 11 civilians injured, Aug 7) · Yemen (Mokha) 11+ killed / 32+ wounded · Bab al-Mandeb (Tihamah, Aug 12) at least 6 killed / 10 wounded per Yemen government · Hormuz-crisis maritime toll ~19 ships damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing",
      delta:
        "A confirmed new death landed in a connected theater: at least three killed and 23 wounded (including two children, three women and six rescuers) in the late-Friday Israeli reprisal on southern Lebanon and the Beqaa after a Hezbollah drone launch — adding to the Lebanon Health Ministry cumulative. On the Iran front the interceptors and evasions held: the carrier and destroyer dodged the anti-ship salvo with no casualty. Hormuz commercial transits ran four-to-six vessels a day (many AIS-dark) against a pre-war 100-120, throughput near a fifth of normal; the Houthi blockade still threatens the Yanbu pipeline reroute; the standing maritime, Bab al-Mandeb and Gulf tolls carry.",
      status:
        "The 'other' ledger worsened by at least three deaths in Lebanon and otherwise held critical in target set. Israel's late-Friday reprisal killed at least three and wounded 23 across five locations in the Tyre and Nabatieh areas and the Beqaa, the June-ceasefire drone-for-airstrike cycle now executed (Health Ministry cumulative ~4,265 / 12,190+, the Wikipedia series 3,371 / 10,129 lagging). On the Iran front the Gulf-host set stayed wide — Jordan, Bahrain, Kuwait and Iraq across the recent cycle — but Day 192 added no verified Gulf fatality as interceptors and ship evasions held. Per §3.5.3 the Houthi Saudi-warship claim, the UAE ballistic-missile threat, and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz commercial throughput held near a fifth of pre-war flow with four-to-six vessels transiting daily, many AIS-dark; war-risk premiums sit multiples above normal and the Iran-Oman corridor stays clouded by fire. The Bab al-Mandeb Tihamah toll (Aug 12) holds at least six killed and ten wounded per Yemen's government; the maritime toll holds ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
    },
  },
  exec:
    "Day 192 gave the war its Iranian answer to 'small potatoes.' As Washington downplayed the fight as 'intermittent strikes,' Iran's parliament speaker and lead negotiator Mohammad Bagher Ghalibaf declared Sunday that Tehran's 'proportionate responses' are over, that further US attacks would draw a 'faster, heavier and more painful' blow, and that Washington should grasp the 'rules of the game have changed before it is too late' — while conceding the war's economic strain of inflation, unemployment and a sliding rial (CNBC, Irish Times, IRNA). The escalation was not only rhetorical: analysts read Iran's first use of anti-ship ballistic missiles, fired at a US carrier and destroyer on Friday and evaded with no casualties per CENTCOM, plus the US strike on three Iranian tankers near Kharg, as a 'tanker war' now settling onto the strait (Al Jazeera, CNN, PBS). The market priced it as anything but small: Brent held near $96 after its biggest weekly gain of the war, Hormuz ran near a fifth of pre-war flow with four-to-six vessels a day transiting AIS-dark, and China stayed defiant as the bank blow slipped behind September 24 (Trading Economics, Al Jazeera, Fortune). The connected fronts hardened — Israel killed at least three in a Lebanon reprisal, the execution wave surged to 78-92 in August, Gaza stayed deadlocked, and IAEA access stayed unrealized (Times of Israel, HRANA, Jordan News). Direction holds escalating; seven-day risk extreme; spillover critical; the thirty-day ceasefire probability holds at 3.",
  implications: [
    {
      title: "Iran answers 'small potatoes' — the proportionality cap comes off",
      body:
        "Tehran gave the President's minimization its rebuttal. Parliament speaker and lead nuclear negotiator Mohammad Bagher Ghalibaf declared Sunday that Iran's 'proportionate responses' to US attacks are over, that Washington should grasp the 'rules of the game have changed before it is too late,' and that any further strike would be met 'faster, heavier and more painful' (CNBC, Irish Times, IRNA). Per §3.5.3 hold the claim against the record from both directions. It is not empty: Iran had, two days earlier, fired anti-ship ballistic missiles at a US carrier and destroyer for the first time, so the retirement of the proportionality cap follows a real move up the ladder. But in the same breath Ghalibaf conceded 'fundamental challenges' — inflation, unemployment, a sliding rial — the first senior acknowledgment that the economic war is landing, which an escalation-dominance posture is meant to obscure. Under the multi-clock framework the political-will and negotiation-capacity clocks are the movers: two principals are now performing for domestic audiences at once, Trump shrinking the war's name to manage his war-powers and midterm exposure, Ghalibaf inflating the threat to cover the home-front strain. Analytical judgment: when Washington says 'small potatoes' and Tehran says 'the rules have changed,' the honest reading sits between the two performances — a war neither side can end and both need to reframe, with the gap on each side the intelligence.",
    },
    {
      title: "The war finds its form — a tanker war on the strait",
      body:
        "The fighting has settled onto the water. Analysts reading the past week — Iran's first anti-ship ballistic missiles fired from Isfahan and Kerman at a US carrier and destroyer, which CENTCOM said the ships evaded with no casualties, and the US strike on three Iranian tankers near Kharg Island — now describe an open 'tanker war' on the Strait of Hormuz (Al Jazeera, CNN, PBS, Euronews). Per §3.5.5 quantify the rung: this is no longer Iranian mine-laying answered by US airstrikes but a two-way naval missile exchange over the chokepoint, with Kpler-tracked commercial transits down to four-to-six vessels a day — many running AIS-dark — against a pre-war 100-120, throughput near a fifth of normal, and war-risk insurance sitting multiples above baseline (Windward, The National, Al Jazeera). The market read it plainly: Brent held near $96 after its biggest weekly gain of the war while Beijing, buyer of the bulk of Iran's oil, vowed to 'take all necessary measures' and the major-Chinese-bank designation slipped again behind the September 24 summit (Trading Economics, Fortune). Analytical judgment: anti-ship ballistic missiles against a carrier group are a categorically higher threat than mines, and the tanker war's logic is attritional and accident-prone — one salvo the ships do not evade, or one laden tanker lost in the fairway, is simultaneously a mass-casualty event and a >$100 Brent session on a drawn-down base.",
    },
    {
      title: "Taiwan: the tanker war lands on the buffered month",
      body:
        "Per §3.5.10 no Iran-front development aimed at Taipei landed on Day 192, but the day sharpened the exposure by naming the threat precisely. The war has now been labeled a tanker war fought on the very chokepoint through which roughly a third of Taiwan's LNG transits — and it intensified in the month, September, that Taiwan said in May it had gas cover only 'through' (Al Jazeera, Energy Connects). The financial clock still points to the same fortnight: the major-Chinese-bank sanction that would rupture the oil-for-money channel remains pinned behind Xi Jinping's September 24 visit, and the IAEA's 'soon' inspection modalities sit around the same window (Jordan News, Fortune), so late September decides both whether Washington fires its economic D-Day and whether Taiwan's buffer is still intact when it does. Per §3.5.5 the arithmetic is unchanged and unforgiving: 95-99% import dependence, roughly a third of LNG through Hormuz, about eleven days of gas cover against some 120 of oil (CSIS). Analytical judgment: a two-way missile war on Hormuz is the exact scenario Taipei's buffer was built to bridge, and the buffer expires the same fortnight the war on the strait is escalating and the bank decision comes due — only supply that never touches Hormuz closes that gap.",
    },
  ],
  casualtyNotes: {
    us:
      "Headline holds 17 KIA / 432 WIA (AP/CENTCOM combat series). DoD DCAS holds 18 killed / 687 wounded all-cause — a wider scope, not a confirmed new combat death; per §3.5.3 keep the combat series and flag DCAS. A fifth quiet day for US casualties: CENTCOM said a carrier and destroyer evaded Iran's Friday anti-ship ballistic-missile salvo with no personnel hurt, but Ghalibaf's retirement of the proportionality cap and the debut of anti-ship missiles raise the odds the next salvo lands. Iran's earlier claim of American service members killed stays denied and uncounted; Trump's 'per ship' rule stays untriggered. CENTCOM's blockade holds at ~86 vessels rerouted, three disabled, two boarded; the escort convoy (~660M+ barrels / ~1,300 vessels since May, ~8-9 mb/d) runs amid live fire with the USS George Washington on station. The $67B supplemental and 50-48 rebuke stay unresolved in recess ahead of the November midterms.",
    israel:
      "Iran-front casualties hold at 56 KIA / 8,652+ WIA; no new Israeli toll. The Hezbollah drone was shot down and no soldiers were hurt, per the IDF; the three killed in Israel's late-Friday Lebanon reprisal are Lebanese and are logged under 'other.' Israel stayed offstage on the US-Iran naval and narrative fight while its Gaza campaign held deadlocked and lethal — the Board of Peace insists no Israeli withdrawal before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap (a connected theater, not folded into the war cumulative; 1,100-1,200+ killed since the October 2025 ceasefire, at least 36 since the disarmament deal). Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold.",
    iran:
      "Official MOH war toll carries pending an update; no new war-front count from Day 192's naval exchange. The day's movement was on the rights thread, kept out of the war toll per §3.1: HRANA's August monthly report documented 78 executions (five women; two men hanged over the January 2026 protests), Iran HRM put the month at 92 (most secret), ten Isfahan protesters were newly sentenced to death, and Amnesty warns many more are at risk since the February 28 attacks. The Sep 1 Kuhestak wedding strike stays independently corroborated as a US-released bomb, but the toll — up to five killed, reportedly including children aged four and sixteen, 68+ wounded — remains an Iranian-source count held pending verification and not folded into the MOH aggregate; Sep 1 military casualties remain unreleased. HRANA 3,636+; Foundation ~3,468; MOH ~3,559 / 27,400+; est. 6,000+. IAEA 'soon' inspections stay short of access; ~440.9 kg 60% + ~184.1 kg 20% HEU likely at Isfahan (§3.5.3).",
    other:
      "The spillover ledger worsened by at least three deaths: Israel's late-Friday Lebanon reprisal killed at least three and wounded 23 (including two children, three women and six rescuers) across five southern and Beqaa locations after a Hezbollah drone launch — the June-ceasefire cycle now executed (Health Ministry cumulative ~4,265 / 12,190+, Wikipedia 3,371 / 10,129 lags). On the Iran front the interceptors and ship evasions held with no verified new fatality. Per §3.5.3 the Houthi Saudi-warship claim, the UAE-missile threat and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz throughput near a fifth of pre-war flow with four-to-six vessels a day (many AIS-dark); the Houthi blockade still threatens the Yanbu pipeline reroute; war-risk premiums multiples above normal; the Iran-Oman corridor stays clouded by fire. Bab al-Mandeb Tihamah (Aug 12) holds at least 6 killed / 10 wounded; maritime toll ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
  },
};

export default data;
