import type { BriefData } from '@/lib/brief-data';

const data: BriefData = {
  escalation: {
    direction: 'escalating',
    risk7d: 'extreme',
    spillover: 'critical',
    rationale: {
      direction:
        "Direction holds escalating on Day 191 as the kinetic ladder stayed paused a fourth day but the war's center of gravity remained on the narrative front — and the front's principal changed. President Trump backed Vice President Vance's refusal to call the conflict a war and dismissed it as 'small potatoes,' pressing the 'defanging' of Iran's nuclear program when a reporter raised the 18 US service members killed and the $37.5 billion spent. Per §3.5.3 read the day as an information-war escalation atop a plateau, not a turn: the campaign is openly continuing, CENTCOM said it had disabled two Iranian tankers and destroyed a third after an Iranian missile salvo at a US carrier group, the IRGC navy kept warning shipping off 'unauthorized routes,' and oil closed its biggest weekly gain of the war near $96. Nothing on Day 191 reversed the return to force; the administration instead worked to shrink the word for it while the market and Beijing priced it up.",
      risk7d:
        "Seven-day risk holds extreme. The mine-laying / strike / retaliation cycle is paused a fourth day, not closed, and the near-term tails stay loaded: a laden-tanker loss in a mined and contested strait, a lost escort convoy, a US casualty from an unintercepted salvo, a strike on a Gulf host, or a named major-Chinese-bank designation could each fire inside the week — and Brent, having just posted an 8-9% weekly gain to a six-week high, sits closer to the >$100 trigger on a drained stock base. The narrative front adds its own tail: the President's 'small potatoes / not a war' framing, set against 18 dead by the administration's own count and the unretracted forensic corroboration of the September 1 wedding strike, keeps the legitimacy cost live and hands Tehran, Beijing and Moscow a running counter-narrative that a market pricing the war up does not support.",
      spillover:
        "Spillover holds critical. No new theater opened on Day 191, which is why it did not worsen outright, but the map is unchanged and wide: Iranian soil under a continuing campaign, both maritime chokepoints, the Gulf host states directly targeted across the recent cycle, the Israel-Gaza and Israel-Lebanon seams, an open Houthi front bearing on the Yanbu pipeline workaround, and a formalized economic front wired to the September 24 US-China summit. Per §3.5.5 the reach still outran the damage — Gulf and Jordanian interceptors held across the retaliation with no verified new fatality — but the target set spanning four-plus Arab states, the collapse of Hormuz throughput to about a fifth of pre-war flow, and China's open defiance of the sanctions threat are the standing signals; the deepening execution wave adds a worsening rights thread kept out of the war toll.",
    },
  },
  events: [
    {
      id: 1,
      direction: 'pivotal',
      importance: 'pivotal',
      source: 'The Washington Post / Fortune / Al Jazeera / NBC Washington (AP)',
      event:
        "The narrative war climbed from the Vice President to the President: Donald Trump backed JD Vance's refusal to call the conflict a war and dismissed it as 'small potatoes' — 'a military conflict because it's small potatoes for us; it's not a big thing' — even as a reporter pressed him on the 18 US service members killed and the $37.5 billion spent, with Trump pointing to the 'defanging' of Iran's nuclear program.",
      summary:
        "Per §3.5.3 the principal now minimizes both the scale and the name of a conflict he is still prosecuting — and the '18 dead' he cited is the DoD DCAS all-cause figure the brief tracks against the 17-death AP/CENTCOM combat series, so the President has put the higher casualty count into his own mouth while shrinking the word for the war.",
      impact:
        "The political-will and coalition-cohesion clocks move: downgrading the war to 'small potatoes' manages the domestic, budgetary and war-powers exposure of an open-ended campaign, but the count Trump used and the unretracted forensic corroboration of the September 1 wedding strike keep the legitimacy cost live and feed the China-Russia counter-narrative.",
    },
    {
      id: 2,
      direction: 'escalating',
      importance: 'high',
      source: 'Trading Economics / The Eastern Herald / CNBC / ABC News',
      event:
        "The market re-priced what Washington downplayed: Brent held near $96 and closed its biggest weekly gain of the war, up roughly 8-9%, as the renewed Hormuz clash reminded traders the strait is not reopening; independent tracking pegged throughput near 4.9 million barrels a day against about 21.6 million pre-war — barely a fifth of normal flow — while the IRGC navy warned all vessels off 'unauthorized routes' after CENTCOM said it had disabled two Iranian tankers and destroyed a third.",
      summary:
        "Per §3.5.5 quantify the gap between framing and tape: a conflict a market prices at an 8-9% weekly move on the world's most important oil chokepoint, with flow at a fifth of pre-war, is not one the tape reads as 'small.'",
      impact:
        "The energy vector's rupture tail stays loaded and closer to the trigger: a laden-tanker loss, a lost escort convoy, or a named major-Chinese-bank designation would send Brent past $100 in a session, with the dual-closure $150-200 tail one sinking away.",
    },
    {
      id: 3,
      direction: 'escalating',
      importance: 'high',
      source: 'Foreign Policy / CNBC / Bloomberg',
      event:
        "China called the bluff on the economic front: Beijing's foreign ministry called its Iran trade 'normal and lawful' and shrugged off Washington's secondary-sanctions threat, while Xi Jinping gave Pezeshkian only a brief, low-profile audience at the SCO ahead of his own September 24 White House visit — the decisive major-Chinese-bank designation still deferred behind that summit, with the rare-earth lever in Beijing's hand.",
      summary:
        "Per §3.5.6 the standing prior holds: China is the plan's hinge, buys the bulk of Iran's oil, and holds the upper hand into the summit — which is precisely why the bank blow keeps slipping and the 'cut off from the dollar' framing runs ahead of the record.",
      impact:
        "The negotiation-capacity and energy-infrastructure clocks move: without Beijing there is no economic D-Day, and Beijing's open defiance ahead of a summit it can shape leaves Washington's central coercive threat pinned to a date it does not control.",
    },
    {
      id: 4,
      direction: 'mixed',
      importance: 'medium',
      source: 'Al Jazeera / OHCHR / Iran HRM',
      event:
        "The connected fronts ran on beneath the narrative war: Gaza held deadlocked — the Board of Peace insisting no Israeli withdrawal before Hamas disarms while Hamas holds it will not act until Israel withdraws, 1,100-1,200+ killed since the October 2025 ceasefire — the IAEA-Iran inspection modalities stayed a technical step short of verified access, and Iran's postwar execution wave deepened, with Iran HRM reporting at least 23 executions between August 23-26 and OHCHR's Türk warning executions are being used to instill fear.",
      summary:
        "Per §3.5.6 the standing priors hold unresolved: the Gaza sequencing deadlock, the unverified nuclear file, and — per §3.1, kept out of the war toll — a worsening rights thread (≥56 executed since March 19, 100+ at risk).",
      impact:
        "The connected fronts neither eased nor were bound by the pause; the war widens on the humanitarian, nuclear and legitimacy vectors even on a day without a confirmed new strike wave.",
    },
  ],
  casualties: {
    us: {
      cumulative:
        'KIA: 17 confirmed · WIA: 432 (AP/CENTCOM combat series; ~96% returned to duty). DoD DCAS all-cause series holds 18 killed · 687 wounded.',
      delta:
        "+0 confirmed on the AP/CENTCOM combat series into Day 191 — a fourth day with no verified new US combat casualty. The count moved into politics instead: defending 'small potatoes,' President Trump cited the 18 US service members killed — the DoD DCAS all-cause figure — so the administration now invokes its own higher number while shrinking the word for the war. Per §3.5.3 the 18th DCAS death is not confirmed hostile, Trump's 'per ship' rule is not triggered, and Iran's earlier claim of American service members killed stays denied and uncounted. The escort convoy (~8-9 mb/d) runs amid live fire with the USS George Washington on station; the blockade holds at eighty-six vessels rerouted, three disabled, two boarded; the IRGC navy is warning shipping off 'unauthorized routes.'",
      status:
        "The headline holds at 17 KIA / 432 WIA on the AP/CENTCOM combat series against the wider DoD DCAS all-cause tally of 18 killed / 687 wounded since February 28. Per §3.5.3 keep the combat figure and flag DCAS — but note the divergence is now a rhetorical fact: pressed on casualties while calling the war 'small potatoes,' the President reached for the 18 figure, putting the higher all-cause number into official use even as it remains unconfirmed as a hostile combat loss and does not, on its own, trigger Trump's 'bridge or power plant per ship' rule. Day 191 added neither a claim nor a count on the US side — a fourth quiet day — but the exposure is unchanged: the escort convoy (~660 million barrels and ~1,300 vessels since May, moving ~8-9 mb/d) runs amid live fire, CENTCOM's blockade holds at roughly eighty-six vessels rerouted, and the IRGC navy's 'unauthorized routes' warning keeps a single unintercepted salvo one event away from the reprisal rule. The $67 billion supplemental and the 50-48 Senate war-powers rebuke stay unresolved in recess ahead of the November midterms, and the 'small potatoes / not a war' framing is itself a move in that political contest.",
    },
    israel: {
      cumulative: 'KIA: 56 (Iran-front 47 + Lebanon-front 9) · WIA: 8,652+',
      delta:
        "+0 on the Iran front; no new Israeli fatalities or wounded there. Israel stayed offstage on the US-Iran narrative fight while its Gaza campaign held deadlocked and lethal — a connected theater, not folded into the war cumulative; strikes since the October 2025 ceasefire 1,100-1,200+, at least 36 of them since the disarmament deal.",
      status:
        "Israeli casualties hold at 56 KIA / 8,652+ WIA on the Iran front; no new Iran-front toll on Day 191. Israel stayed offstage on the US-Iran narrative contest while its own fronts stayed hot: the US-led Board of Peace insists no Israeli withdrawal from Gaza will occur before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap — the disarm-first / withdraw-first sequencing unresolved, with 1,100-1,200+ Palestinians killed since the October 2025 ceasefire and at least 36 since the disarmament deal, a connected theater the series does not fold into the war cumulative. In Lebanon Israel kept striking Hezbollah and Hamas 'targets,' the threatened reprisal unexecuted, and UNIFIL's Khardali-Litani handover to the Lebanese Army's 7th Brigade carries. Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold — Israel acts on its own clock, outside the US-Iran framework.",
    },
    iran: {
      cumulative:
        'Foundation of Martyrs ~3,468 KIA · HRANA 3,636+ documented (1,221 mil / 1,701 civ / 714 unclassified) · MOH ~3,559 killed / 27,400+ wounded · US-Israeli est. 6,000+ · 3.2M displaced',
      delta:
        "No update to the official war toll. The contested September 1 Kuhestak wedding strike carries per §3.1 dual-sourcing — independently corroborated by NYT visual analysis as a US-released bomb, but the toll (up to five killed, reportedly including children aged four and sixteen, 68+ wounded) remains an Iranian-source count held pending verification and not folded into the MOH headline; September 1 military casualties (sixteen minelayers, IRGC coastal sites) remain unreleased. The separate rights thread deepened: Iran HRM reported at least 23 executions between August 23-26 and OHCHR's Türk says executions are being used to instill fear (≥56 since March 19, 100+ at risk).",
      status:
        "The official Iranian war toll carries pending an update; Day 191 added no new war-front count. The day's movement was on the rights thread, kept out of the war cumulative per §3.1: Iran Human Rights Monitor reported at least 23 executions across the country between August 23 and 26 — roughly one every four hours — and UN High Commissioner Volker Türk again warned that executions are being used to instill fear and suppress dissent, with at least 56 people executed on national-security charges since March 19 and more than 100 at risk. The contested civilian figure holds: the September 1 Kuhestak wedding strike is independently corroborated as a US-released bomb, but the toll of up to five killed (reportedly including children aged four and sixteen) and 68+ wounded remains an Iranian-source count held pending verification and not folded into the MOH aggregate; September 1 military casualties (sixteen minelayers, IRGC sites across Bandar Abbas, Chabahar, Qeshm, Konarak and Sirik) remain unreleased. Cumulative HRANA stands at 3,636+ with its understatement caveat, Foundation of Martyrs ~3,468, MOH ~3,559 / 27,400+, and US and Israeli estimates run to 6,000+. The IAEA-Iran modalities stay a technical step, not verified access, with Iran's 'only after a deal' framing intact; the ~440.9 kg of 60% HEU plus ~184.1 kg of 20% stays unverified and likely at Isfahan, ISIS flagging enough for up to ten weapons if further enriched.",
    },
    other: {
      cumulative:
        "Lebanon source-split: Health Ministry ~4,265 / 12,190+ vs Wikipedia 3,371 / 10,129 · Iraq 148+ KIA / 402+ WIA · Gulf 33+ KIA / 85+ WIA (Kuwait 10 killed / 115 injured; Saudi Arabia 11 civilians injured, Aug 7) · Yemen (Mokha) 11+ killed / 32+ wounded · Bab al-Mandeb (Tihamah, Aug 12) at least 6 killed / 10 wounded per Yemen government (Houthis unconfirmed) · Hormuz-crisis maritime toll ~19 ships damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing",
      delta:
        "The spillover ledger held critical without a confirmed new death: the Gulf-host target set stayed wide but unfired-on in the past day, Gulf and Jordanian air defenses having held across the recent retaliation with no verified fatality. Hormuz throughput was pegged near 4.9 million barrels a day against about 21.6 million pre-war — barely a fifth of normal — with the IRGC navy warning vessels off 'unauthorized routes'; the Houthi blockade still threatens the Yanbu pipeline reroute; the standing maritime, Lebanon and Bab al-Mandeb tolls carry.",
      status:
        "The 'other' ledger held critical in target set without a confirmed new death. The Gulf-host set stayed wide — Jordan, Bahrain, Kuwait and Iraq across the recent cycle — but the interceptors held and Day 191 added no verified fatality. Per §3.5.3 the standing Houthi Saudi-warship claim, the UAE ballistic-missile threat, and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz commercial throughput was pegged near 4.9 million barrels a day against about 21.6 million pre-war — roughly a fifth of normal flow — with the IRGC navy warning all vessels off 'unauthorized routes' and threatening any 'suspicious movement.' War-risk premiums hold 3-10% of hull value and the Iran-Oman corridor stays clouded by fire. In Lebanon the Aug 15 strike that killed at least eleven including three children (Health Ministry cumulative ~4,265 / 12,190+, the Wikipedia series 3,371 / 10,129 lagging) holds as an unfulfilled Hezbollah-Israel threat exchange as UNIFIL's Khardali-Litani handover carries. The Bab al-Mandeb Tihamah toll (Aug 12) holds at least six killed and ten wounded per Yemen's government. The maritime toll holds ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
    },
  },
  exec:
    "Day 191 held the kinetic pause a fourth day, but the narrative war climbed from the Vice President to the President. Donald Trump backed JD Vance's refusal to call the conflict a war and dismissed it as 'small potatoes' — 'a military conflict because it's small potatoes for us; it's not a big thing' — even as a reporter pressed him on the 18 US service members killed and the $37.5 billion spent, with Trump pointing to the 'defanging' of Iran's nuclear program (Washington Post, Fortune, Al Jazeera, NBC Washington). Per §3.5.3 the framing sits against the record: eighteen dead is the DoD DCAS all-cause figure this brief has carried against the 17-death AP/CENTCOM combat series, so the administration now invokes its own higher number while shrinking the word for the war. Beneath the messaging the market re-priced what Washington downplayed: Brent held near $96 and closed its biggest weekly gain of the war, up roughly 8-9%, as independent tracking pegged Hormuz throughput near 4.9 million barrels a day against about 21.6 million pre-war — barely a fifth of normal — with the IRGC navy warning shipping off 'unauthorized routes' (Trading Economics, Eastern Herald, ABC News). China shrugged off the sanctions threat and kept Pezeshkian at arm's length ahead of the September 24 Trump summit, the major-Chinese-bank blow still deferred (Foreign Policy, CNBC). Gaza held deadlocked, the IAEA modalities short of access, and the execution wave deepened (Al Jazeera, OHCHR, Iran HRM). Direction holds escalating; seven-day risk extreme; spillover critical; the thirty-day ceasefire probability holds at 3.",
  implications: [
    {
      title: "The narrative war reaches the Oval Office — 'small potatoes' against eighteen coffins",
      body:
        "With the guns quiet a fourth day, the information war climbed from the Vice President to the President. Trump told reporters he agrees with JD Vance that the fighting with Iran is not a war and called it 'small potatoes for us — not a big thing,' pointing to the 'defanging' of Iran's nuclear program when pressed on the 18 US service members killed and the $37.5 billion spent (Washington Post, Fortune, NBC Washington). Per §3.5.3 hold the claim against the record on two counts. The label first: the 'small potatoes / not a war' framing sits over a campaign that struck Iranian tankers days earlier and whose IRGC counterpart is still warning shipping off the strait — the guns are paused, not holstered. Then the number: eighteen is the DoD DCAS all-cause figure this brief has carried against the 17-death AP/CENTCOM combat series, so the President has now put the higher casualty count into his own mouth while shrinking the word for the conflict — the divergence the brief tracks is now a rhetorical fact. Under the multi-clock framework the political-will and coalition-cohesion clocks are the movers: downgrading the war manages the war-powers, budget and midterm exposure of an open-ended fight, but the unretracted forensic corroboration of the September 1 wedding strike keeps the legitimacy cost live. Analytical judgment: when the principal minimizes both the scale and the name of a conflict he is still prosecuting, the gap between framing and record is the intelligence — and 'small potatoes' against eighteen coffins is the widest that gap has been.",
    },
    {
      title: "The market re-prices what Washington downplays — and Beijing calls the bluff",
      body:
        "The clearest rebuttal to 'small potatoes' came from the tape. Brent held near $96 and booked its biggest weekly gain of the war — roughly 8-9% — as the renewed Hormuz clash reminded traders the strait is not reopening (Trading Economics, Eastern Herald, CNBC). Per §3.5.5 quantify it: throughput is pegged near 4.9 million barrels a day against about 21.6 million pre-war, barely a fifth of normal flow on a global stock base drawn down by months of reduced transits, with the IRGC navy warning all vessels off 'unauthorized routes.' The economic architecture behind the price ran on: China shrugged off Washington's sanctions threat, its foreign ministry calling the Iran trade 'normal and lawful,' and Xi kept Pezeshkian at arm's length ahead of the September 24 White House summit while the decisive major-Chinese-bank designation stayed deferred behind it (Foreign Policy, CNBC). Per §3.5.6 the standing prior holds: China is the plan's hinge, buys the bulk of Iran's oil, and — with the rare-earth lever in hand — holds the upper hand into the summit, which is exactly why the bank blow keeps slipping. Analytical judgment: the President downplays the war in words while the oil market and Beijing both price it as consequential; the rupture tail is loaded — a laden-tanker loss, a lost escort convoy or a named Chinese bank sends Brent through $100 in a session — and 'small potatoes' is a bet the tape is not taking.",
    },
    {
      title: "Taiwan: the buffered month runs down as oil books its biggest weekly gain of the war",
      body:
        "Per §3.5.10 no Iran-front development aimed at Taipei landed on Day 191, but the exposure sharpened as the physical and financial clocks kept converging. The physical one: September — the month Taiwan said in May it had gas cover 'through' — is drawing down with Brent at a six-week high near $96 after its biggest weekly gain of the war, Hormuz flowing near a fifth of pre-war volume, and the corridor clouded by fire (Energy Connects, Eastern Herald). The financial one nears its date: the major-Chinese-bank sanction that would rupture the oil-for-money channel is still pinned behind Xi Jinping's September 24 visit (Foreign Policy), so the same late-September fortnight that ends Taiwan's gas buffer also decides whether Washington fires its economic D-Day — and Beijing's rare-earth leverage makes the bank blow the likeliest casualty of the summit. Per §3.5.5 the arithmetic is unchanged and unforgiving: 95-99% import dependence, roughly a third of Taiwan's LNG through Hormuz, about eleven days of gas cover against some 120 of oil (CSIS). Analytical judgment: Taipei's early hedge toward US and Australian LNG and roughly 60% US crude was the right call, but a buffer is a countdown, not a solution — and with oil posting its biggest weekly gain of the war as the strait runs at a fifth of normal and the buffer expires in the same fortnight the bank decision comes due, only supply that never touches Hormuz closes the gap.",
    },
  ],
  casualtyNotes: {
    us:
      "Headline holds 17 KIA / 432 WIA (AP/CENTCOM combat series). DoD DCAS holds 18 killed / 687 wounded all-cause — a wider scope, not a confirmed new combat death; per §3.5.3 keep the combat series and flag DCAS. Day 191 turned the divergence into a rhetorical fact: pressed on casualties while calling the war 'small potatoes,' Trump cited the 18 figure, putting the higher all-cause number into official use even as the 18th death is unconfirmed as hostile and does not trigger Trump's 'per ship' rule. A fourth quiet day for US casualties; Iran's earlier claim of American service members killed stays denied and uncounted. CENTCOM's blockade holds at ~86 vessels rerouted, three disabled, two boarded; the escort convoy (~660M+ barrels / ~1,300 vessels since May, ~8-9 mb/d) runs amid live fire with the USS George Washington on station; the IRGC navy is warning shipping off 'unauthorized routes.' The $67B supplemental and 50-48 rebuke stay unresolved in recess ahead of the November midterms.",
    israel:
      "Iran-front casualties hold at 56 KIA / 8,652+ WIA; no new Iran-front toll. Israel stayed offstage on the US-Iran narrative contest while its Gaza campaign held deadlocked and lethal — the Board of Peace insists no Israeli withdrawal before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap (a connected theater, not folded into the war cumulative; 1,100-1,200+ killed since the October 2025 ceasefire, at least 36 since the disarmament deal). Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold.",
    iran:
      "Official MOH war toll carries pending an update; no new war-front count on Day 191. The day's movement was on the rights thread, kept out of the war toll per §3.1: Iran HRM reported at least 23 executions Aug 23-26 and UN's Türk again warned executions are used to instill fear (≥56 since Mar 19, 27 protest-linked, 100+ at risk). The Sep 1 Kuhestak wedding strike stays independently corroborated as a US-released bomb, but the toll — up to five killed, reportedly including children aged four and sixteen, 68+ wounded — remains an Iranian-source count held pending verification and not folded into the MOH aggregate; Sep 1 military casualties remain unreleased. HRANA 3,636+; Foundation ~3,468; MOH ~3,559 / 27,400+; est. 6,000+. Iran's claims of US service members killed and eight MQ-9s destroyed stay logged, not counted (§3.5.3). The IAEA-Iran modalities stay a technical step, not verified access; ~440.9 kg 60% + ~184.1 kg 20% HEU likely at Isfahan.",
    other:
      "The spillover ledger held critical without a confirmed new death: the Gulf-host target set stayed wide but unfired-on in the past day, Gulf and Jordanian interceptors having held across the recent retaliation with no verified fatality. Per §3.5.3 the Houthi Saudi-warship claim, the UAE-missile threat and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz throughput pegged near 4.9 mb/d against ~21.6 pre-war — about a fifth of normal — with the IRGC navy warning vessels off 'unauthorized routes'; the Houthi blockade still threatens the Yanbu pipeline reroute; war-risk premiums 3-10% of hull; the Iran-Oman corridor stays clouded by fire. Lebanon's Aug 15 eleven-death strike (Health Ministry ~4,265 / 12,190+, Wikipedia 3,371 / 10,129 lags) holds as an unfulfilled threat exchange; Bab al-Mandeb Tihamah (Aug 12) holds at least 6 killed / 10 wounded. Maritime toll ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
  },
};

export default data;
