import type { BriefData } from '@/lib/brief-data';

const data: BriefData = {
  escalation: {
    direction: 'mixed',
    risk7d: 'extreme',
    spillover: 'critical',
    rationale: {
      direction:
        "Direction holds mixed, but the composition of the mix inverted inside twenty-four hours. The deferral-as-answer prior booked yesterday is under immediate and direct test: Witkoff and Kushner met the Iranian delegation through mediators for roughly three hours on the Assembly sidelines, Trump called the meeting very good and very productive, Rubio said the president is open to meeting Pezeshkian, and the State Department approved protection for Araghchi in New York. Against that, Pezeshkian used the rostrum to hold up photographs of Khamenei and of schoolgirls he said were killed at Minab, called the United States the terrorist, and accepted negotiation only without the language of force. Per §3.5.3 both the American optimism and the Iranian conditions are carried as the actors' own claims.",
      risk7d:
        "Seven-day risk holds extreme because nothing kinetic or economic has been stood down and the week's hard dates are unchanged. The 1737 Committee Panel of Experts mandate lapses September 26-27 with no chair seated. The Trump-Xi summit convenes today with Chinese bank designation unresolved. Brent reversed four sessions of decline in a single day, rising 3.86% to settle at $103.08, and the ten-year Treasury yield hit 5.11%, its highest since 2007, with October rate-rise odds jumping to 66.4%. Yemen produced the week's first published casualty claims and the UN forecast displacement rising from over 130,000 to more than 230,000. Talks in New York are mediated and indirect; no ceasefire, no blockade pause and no lifted designation has followed them.",
      spillover:
        "Spillover holds critical and shifted from the chokepoint to the ledger. The waterway is the one axis that improved; the financing axis deteriorated sharply, with a 19-year high in the ten-year yield, a 30-year mortgage at 7.26% and input costs rising on energy — an American domestic cost now running directly into the midterm cycle the president has made the hinge of his Iran policy. The Yemen axis reopened after six silent days with Houthi claims of a Saudi strike killing six in Mocha including two children and nine detainees in a northern prison, none of it independently confirmed and none of it answered by Riyadh. The Iranian internal ledger is unchanged and unrelieved by anything said in New York.",
    },
  },
  events: [
    {
      id: 1,
      direction: 'pivotal',
      importance: 'high',
      source: 'Axios / Al Jazeera / Fox News / Business Standard / Bloomberg via BusinessMirror',
      event:
        "President Trump said US officials held a roughly three-hour meeting with the Iranian delegation on the sidelines of the General Assembly in New York — envoy Steve Witkoff and Jared Kushner for the United States, Foreign Minister Abbas Araghchi for Iran — conducted through mediators rather than directly. Trump called it a very good meeting, said Witkoff and Kushner had a very productive meeting with mediators of Iran, and added that a deal was nearing. Secretary of State Marco Rubio said the president is open to meeting Pezeshkian while both are in New York. The State Department had separately approved protection for Araghchi after reviewing threats against him.",
      summary:
        "Per §3.5.11 this is the day's single pivotal item. Per §3.5.6 the deferral-as-answer prior booked on Day 208 — that Washington would answer Iranian paper with a calendar rather than a reply — is under direct test within one day of being written, and is provisionally suspended rather than retired: the rostrum said November, the sidelines opened a channel. Per §3.5.3 very productive is the convening party's characterisation of its own meeting, and the operative fact is that the talks were mediated and indirect, which is the same architecture that produced and then lost Salalah.",
      impact:
        "For the first time since Salalah lapsed the United States and Iran are in the same building talking through mediators about ending the war, with no ceasefire, no blockade pause and no designation lifted to show for it yet.",
    },
    {
      id: 2,
      direction: 'de-escalating',
      importance: 'high',
      source: 'Reuters via US News / CNBC / Al Jazeera / Ynet / Jerusalem Post',
      event:
        "A senior Iranian official told Reuters that Tehran can reopen the Strait of Hormuz within seven days if the United States eases military pressure and lifts the blockade of Iranian ports, and that the Iranian delegation in New York carries full authority to revive diplomacy. The conditions were set out as a halt to what Tehran calls American acts of aggression, an end to the naval blockade and economic warfare, and the release of frozen Iranian assets, with details discussable through mediators. Washington, the official said, must announce that it wants a diplomatic resolution, make that official, then agree a timeline. Tehran says it delivered its proposal via mediators on September 1.",
      summary:
        "Per §3.5.5 the quantified offer is the finding: seven days, against a CENTCOM claim from Day 208 that the main lanes are already clear of mines. Those two statements cannot both be fully true, and the gap between them is the information. Either Iranian control of the strait is now largely declaratory and the seven-day offer sells something Tehran no longer holds, or the clearance is narrower than announced. Per §3.5.3 both are claims by the party with the strongest interest in the claim.",
      impact:
        "Iran has for the first time attached a specific number of days and a specific price to reopening the strait, converting an open-ended threat into a tradeable item days after the asset behind it was reported neutralised by force.",
    },
    {
      id: 3,
      direction: 'escalating',
      importance: 'high',
      source: 'CNBC / Al Jazeera / Foreign Policy / UN News / Washington Post / Gulf News',
      event:
        "President Pezeshkian addressed the 81st General Assembly in a defiant speech blaming the United States and Israel for global instability and for illegal attacks on Iranian civilians and infrastructure. He held up a photograph of Ayatollah Ali Khamenei, whom he said was assassinated without legal framework or reason in the February joint US-Israeli strike, and photographs of schoolgirls he said were killed in an American attack on their school at Minab, alongside images of their graves. He told the chamber that the American president called Iranians terrorists but that Iranians are the victims of terrorists, and that the nuclear weapon is in Israel but the inspectors are in Iran. He said Tehran is ready for dialogue, diplomacy and negotiations without accepting the language of force. Iranian officials separately called Trump's threats a sign of strategic desperation.",
      summary:
        "Per §3.1 rule 3 the divergence inside the same delegation is the information: the head of state rejected the language of force from the rostrum on the same day his foreign minister spent three hours with American envoys through mediators. Per §3.5.6 the exit-not-answer prior is sharpened — Minab, whose elevated Pentagon probe remains unpublished, has now been entered into the General Assembly record as photographic evidence by the head of the Iranian state.",
      impact:
        "Tehran has separated its public position from its negotiating position in public, which preserves the channel while making any American concession legible domestically in Iran as a victory rather than a capitulation.",
    },
    {
      id: 4,
      direction: 'escalating',
      importance: 'high',
      source: 'CNBC / CNN Business / NBC News / Trading Economics',
      event:
        "Brent crude reversed four consecutive sessions of decline, the front-month contract rising 3.86% to settle at $103.08 a barrel and separately quoted at $101.61, up 2.37%. The ten-year US Treasury yield surged fifteen basis points to 5.11% and touched 5.13%, its highest since 2007, driven by energy-led input costs, September business activity expanding at the fastest rate since July 2021 on S&P Global data, and Fed Governor Michael Barr signalling that further policy adjustments are likely. Odds of another quarter-point increase in October rose to 66.4% from 55% on CME FedWatch, and the average thirty-year fixed mortgage rate jumped to 7.26%, the highest since January 2025.",
      summary:
        "Per §3.5.6 the contested-price-record prior applies again: two published Brent settlements for the same session differ by roughly $1.50, and the series carries both rather than choosing. Per §3.5.5 the reversal is the finding — the entire four-session unwind of the Riyadh-strike and Petroline premium was recovered in one session on diplomatic headlines, which is the market pricing the possibility of a deal rather than the fact of cleared lanes.",
      impact:
        "The political-will clock and the energy clock have coupled directly: a 19-year high in the benchmark American borrowing rate and a 7.26% mortgage now sit inside the same midterm cycle the president has made the precondition for an Iran deal.",
    },
    {
      id: 5,
      direction: 'escalating',
      importance: 'medium',
      source: 'Japan Times / UN via Japan Times / CFR Global Conflict Tracker / Al Jazeera',
      event:
        "Yemen's Houthis accused Saudi Arabia of a wave of strikes that killed civilians and prison inmates, breaking six days in which neither capital published any figure. Houthi media reported a Saudi airstrike at Mocha that killed six people including two children, and a strike on a northern Yemeni prison that killed nine detainees. Neither claim is independently confirmed, and Riyadh has neither confirmed nor denied them nor published any answer to the September 19 strike on its own capital. The United Nations forecast that displacement driven by the Houthi seizure of the Red Sea coast could rise from more than 130,000 today to more than 230,000 in coming months.",
      summary:
        "Per §3.1 these are Houthi claims carried as claims and are not folded into the cumulative until corroborated; the al-Hazm precedent from September 7 is the governing analogue. Per §3.5.5 the displacement figure is the harder number and it revises the series upward twice over: from 112,000 carried since mid-September to more than 130,000 now, with a UN projection of more than 230,000, against IOM stocks already reported near depletion.",
      impact:
        "The theatre with no negotiating channel, no mediator and no casualty accounting is the one the UN now projects will nearly double its displaced population, while every diplomatic instrument in play this week is addressed to the Iranian file.",
    },
  ],
  casualties: {
    us: {
      cumulative:
        'KIA: 17 confirmed · WIA: 432 (AP/CENTCOM combat series; ~96% returned to duty). DoD DCAS all-cause series holds 18 killed · 687 wounded. The Intercept reports the Pentagon acknowledges 410 killed or wounded since July 7.',
      delta:
        "+0 confirmed on the AP/CENTCOM combat series into Day 209 — a twenty-second consecutive day with no verified new US combat casualty, two of them unrecorded. The day's American activity was diplomatic and financial rather than kinetic: the three-hour mediated meeting between Witkoff, Kushner and the Iranian delegation, Rubio's statement that the president is open to meeting Pezeshkian, and a ten-year Treasury yield at a 19-year high driven partly by the energy prices this war produces.",
      status:
        "The headline holds at 17 KIA / 432 WIA on the combat series against DCAS 18 / 687 all-cause and The Intercept's Pentagon figure of 410 killed or wounded since July 7; per §3.5.3 keep the combat figure and flag both divergences. Aggregator ranges of 19-23 killed and 831-900 wounded against a CENTCOM injured figure of 820 are recorded as a third unreconciled series rather than adopted. The elevated Pentagon probe into the Minab school strike remains unpublished, and Minab is now on the General Assembly record in photographs held up by Iran's head of state. Escort corridor and blockade series carry: ~40 vessels a day, ~14 mb/d, 105 redirected, 4 disabled, 26 humanitarian transits. The Senate has still not taken up the House's 220-204 war powers resolution and the $67B supplemental is unresolved, both running into a midterm cycle in which the thirty-year mortgage has reached 7.26%.",
    },
    israel: {
      cumulative: 'KIA: 56 (Iran-front 47 + Lebanon-front 9) · WIA: 8,652+',
      delta:
        "+0 on the Iran front and no new Israeli military fatality. Israel produced no published statement on Day 209 and was absent from the New York channel entirely: the three-hour meeting on ending the war and reopening the strait was conducted between American envoys and Iranian mediators with no Israeli participation reported.",
      status:
        "Israeli casualties hold at 56 KIA / 8,652+ WIA on the Iran front. Per §3.5.6 the Israeli-independence prior is reinforced by absence rather than by statement: Katz's security-zone doctrine from Day 208 — forces remaining in Gaza, Lebanon and Syria, with displacement, destruction and occupation described as the language Hamas and Hezbollah understand — stands unretracted while Washington negotiates an end to the war through mediators without Israel in the room, five weeks before the October 27 Israeli election. Lebanon's toll accumulates outside the Iran-front ledger at roughly 4,300 killed and 12,200+ wounded since March, with the Lebanese army recording roughly 7,700 violations of the June 26 framework. Katz ties withdrawal from the ~700 sq km belt and the Ali al-Taher ridge to nationwide Hezbollah disarmament, a condition no New York instrument addresses. The Gaza ceasefire holds broadly.",
    },
    iran: {
      cumulative:
        'Foundation of Martyrs ~3,468 KIA · HRANA 3,636+ documented (1,221 mil / 1,701 civ / 714 unclassified) · MOH ~3,559 killed / 27,400+ wounded · US-Israeli est. 6,000+ · 3.2M displaced',
      delta:
        "No new official Iranian war toll on Day 209. Tehran's casualties entered the record in a different form: Pezeshkian held up photographs at the General Assembly of Khamenei, killed in the February strike, and of schoolgirls he said were killed in the American attack on their school at Minab, alongside images of their graves. No confirmed Iranian ballistic or drone attack on a host state has been recorded since the night of September 8-9, a pause now in its fifteenth day.",
      status:
        "The war-casualty series and the separate protest ledger continue to be carried apart; per §3.1 neither is folded into the other. The Iran Human Rights roster published on Day 208 — more than 4,200 named dead since the December 28 shopkeepers' strike, including 420 women and 281 people under eighteen — carries unchanged. Nothing offered in New York touches the internal ledger: the rial past two million to the dollar and down roughly 44% in six months, official inflation 69.9% against household inflation near 89%, unemployment 9.1%, average monthly salary near $125 against basic spending near $450, 32 medicine categories short and loadings down approximately 85%. The seven-day Hormuz offer and the demand for frozen assets are addressed to exactly this ledger, which is why Tehran priced them. Rights thread carries: ≥59 arbitrary executions March 18 to end August; 23 executions August 23-26. The IAEA referral (23-3) carries alongside the September 9 Cairo modalities agreement; the Panel of Experts mandate lapses September 26-27. The Supreme Leader has not been seen in roughly six months.",
    },
    other: {
      cumulative:
        'Yemen/Houthi-Saudi ~3,598 KIA · 10,804+ WIA across Lebanon (~4,300+/12,200+), Gulf states (33+/~103+ Saudi; Kuwait 10/115), Iraq (148+/402+), maritime (~19 damaged / 7 abandoned / 2 captured / ~18 seafarers) and Mokha/coast (11+/32+)',
      delta:
        "The six-day silence broke with claims rather than confirmations. Houthi media reported a Saudi airstrike at Mocha killing six people including two children, and a strike on a northern Yemeni prison killing nine detainees. Per §3.1 both are carried as Houthi claims and are held outside the cumulative pending corroboration, on the al-Hazm precedent. Riyadh published no confirmation, no denial, and no answer to the September 19 capital strike, a seventh day. Displacement is revised upward: the UN puts it above 130,000 against the 112,000 carried, and forecasts more than 230,000 in coming months, with IOM stocks near depletion.",
      status:
        "Yemen remains the war's independent escalation generator and is the only theatre with no channel in New York. The Houthis hold Mocha, Mayun, the Hanish islands and Yemen's Red Sea coast; Bab al-Mandeb carries about 12% of global trade, 11% of seaborne oil and 8% of LNG, with no formal closure declared. Per §3.5.6 the condemnation-without-contribution prior is in its seventh day of direct test: Saudi Arabia has absorbed a strike on its capital, is accused of killing children and prisoners in retaliation, and has published nothing on either. The Saudi energy picture is improved but not recovered: the East-West pipeline has restarted with pumping stations under repair, Yanbu loadings stay depressed, and the shortfall is routed through Hormuz rather than replaced. Regional flows averaged 17.1 mb/d over ten days. The IOM shipwreck toll stays out of the cumulative.",
    },
  },
  exec:
    "Day 209 is the day the sidelines contradicted the rostrum. Twenty-four hours after Trump told the General Assembly he was weighing whether to annihilate Iran and predicted a deal only after November 3, he said American officials had held a roughly three-hour meeting with the Iranian delegation in New York — Witkoff and Kushner for Washington, Araghchi for Tehran, through mediators — called it very good and very productive, and said a deal was nearing (Axios, Al Jazeera, Fox News, Bloomberg). Rubio said the president is open to meeting Pezeshkian; the State Department had already approved protection for Araghchi. A senior Iranian official told Reuters Tehran can reopen the Strait of Hormuz within seven days if Washington eases military pressure, lifts the blockade of Iranian ports and releases frozen assets — a specific number of days and a specific price, offered days after CENTCOM said the lanes were already cleared by force. Pezeshkian meanwhile used the rostrum to hold up photographs of Khamenei and of schoolgirls he said were killed at Minab, said the nuclear weapon is in Israel but the inspectors are in Iran, and accepted negotiation only without the language of force (CNBC, Foreign Policy, UN News). Markets reversed: Brent recovered four sessions of losses in one, up 3.86% to $103.08, and the ten-year Treasury yield hit 5.11%, its highest since 2007, with the thirty-year mortgage at 7.26% (CNN Business, NBC News). Yemen broke six days of silence with Houthi claims of a Saudi strike killing six at Mocha including two children and nine detainees in a northern prison, and the UN forecast displacement rising past 230,000. Direction holds mixed; seven-day risk extreme; spillover critical; the thirty-day ceasefire probability rises from 2 to 6.",
  implications: [
    {
      title: 'The deferral prior lasted one day — and the channel it hid is the real news',
      body:
        "Day 208 booked a prior that Washington would answer Iranian paper with a calendar rather than a reply. Within twenty-four hours Witkoff and Kushner sat with Araghchi for three hours through mediators, Trump called it very productive and said a deal was nearing, Rubio floated a Pezeshkian meeting, and the State Department had already cleared protection for the Iranian foreign minister (Axios, Business Standard, Fox News, Al Jazeera). Per §3.5.6 the prior is suspended rather than retired: a channel is not an agreement, the talks were mediated and indirect, and the November framing came from the same mouth on the same trip. Per §3.5.3 very productive is the convening party's characterisation of a meeting only it has described. The analytically honest reading is that the rostrum speech was addressed to a domestic electorate and the sidelines to Tehran, and that both are true simultaneously. Analytical judgment: under the multi-clock framework the negotiation-capacity clock has restarted after eight weeks dead, but it restarted in the same architecture — mediated, indirect, unwritten — that produced Salalah and then lost it in less time than the six weeks Washington has now built into its own calendar. The thirty-day ceasefire probability rises from 2 to 6, which is a channel reopening, not a war ending.",
    },
    {
      title: 'Iran priced a strait it may no longer control, and the price is the ledger',
      body:
        "A senior Iranian official told Reuters Tehran can reopen Hormuz in seven days against a halt to American operations, an end to the blockade and economic warfare, and the release of frozen assets (Reuters via US News, CNBC, Ynet). Set that beside CENTCOM's Day 208 statement that the main lanes are already clear of Iranian mines and flows are at a six-month high, and the two cannot both be fully true. Per §3.5.5 the gap is the finding: either the clearance is narrower than announced, or Iran is selling an asset it has largely lost and knows it. The composition of the ask settles which reading matters. Tehran did not ask for sanctions relief in the abstract; it asked for the blockade lifted and the assets released — the two items that move a rial past two million to the dollar, 69.9% official inflation and crude loadings down 85%, against an average wage near $125 and basic household spending near $450. Analytical judgment: the leverage-restoration prior booked on Day 208 predicted Tehran would move to rebuild leverage rather than wait on it. It has instead moved to monetise the residual, which is the behaviour of a party negotiating from a worsening position and reading its own economic clock as the binding one. That makes this channel more likely to produce something than Salalah, and more likely to produce something Tehran cannot sell at home.",
    },
    {
      title: 'Taiwan: the substitution chain is now running through American molecules',
      body:
        "This is the fresh Taiwan-relevant development. QatarEnergy has bought as many as 33 US LNG cargoes on the spot market in 2026 to serve Asian customers, with cargoes in transit to South Korea, Taiwan and India, after Iranian missile strikes on two Ras Laffan trains in March cut roughly 12.8 million tonnes a year, about 17% of Qatari exports (OilPrice.com, IndexBox, Kpler). Per §3.5.6 the substitution-chain prior is borne out in an unexpected direction: the chain did not fail, it relocated, and Taipei is now indirectly supplied by American liquefaction routed through a Qatari contract rather than by Qatari liquefaction. That is supply, but it is supply with two new exposures — the cargoes are priced against a Brent that recovered 3.86% in one session on a diplomatic headline, and they depend on Qatar continuing to buy for resale rather than declaring force majeure, which it has already extended once. Taipei imports about 96% of its energy, takes roughly half its generation from LNG, and holds about eleven days of reserve against a fourteen-day floor not due until 2027 (IFRI, Atlantic Council, CSIS). Analytical judgment: the May-assessed secured window expires in six days and the replacement is a resale arrangement, not a contract — which means Taiwan's October supply is now exposed to a Qatari commercial decision that no New York negotiation addresses.",
    },
  ],
  casualtyNotes: {
    us:
      "Headline holds 17 KIA / 432 WIA (AP/CENTCOM combat series); DCAS holds 18 / 687 all-cause; The Intercept's Pentagon figure of 410 killed or wounded since July 7 carries. Aggregator ranges of 19-23 killed and 831-900 wounded, against a CENTCOM injured figure of 820, are recorded per §3.5.3 as a third unreconciled series and not adopted. Twenty-second consecutive quiet day, two unrecorded. Day 209's American developments were diplomatic and financial: the three-hour mediated Witkoff-Kushner-Araghchi meeting, Rubio's opening to a Pezeshkian meeting, State's clearance of protection for Araghchi, and a ten-year Treasury at 5.11% with the thirty-year mortgage at 7.26%. The elevated Pentagon probe into Minab remains unpublished and Minab is now on the General Assembly record in photographs. Escort corridor holds at ~40 ships/day and ~14 mb/d; blockade series 105 redirected / 4 disabled / 26 humanitarian. Senate has not taken up the 220-204 House resolution; the $67B supplemental is unresolved.",
    israel:
      "Iran-front casualties hold at 56 KIA / 8,652+ WIA; no new toll and no published Israeli statement on Day 209. The significant Israeli fact is absence: the three-hour New York channel on ending the war and reopening the strait ran between American envoys and Iranian mediators with no reported Israeli participation, five weeks before the October 27 Israeli election. Katz carries unretracted from Day 208: forces remain in security zones in Gaza, Lebanon and Syria, displacement, destruction and occupation are described as the language Hamas and Hezbollah understand, and no withdrawal from the ~700 sq km belt or the Ali al-Taher ridge until Hezbollah is disarmed nationwide — a condition no instrument discussed in New York addresses. The Lebanese army records ~7,700 violations of the June 26 framework; Lebanon's separate ledger runs ~4,300+ killed / 12,200+ wounded. Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold and are reinforced by the absence.",
    iran:
      "Official MOH war toll carries unchanged; Day 209 produced no new war count and no confirmed Iranian launch against a host state since September 8-9, now a fifteen-day pause. Iranian casualties entered the record rhetorically: Pezeshkian held up photographs at the General Assembly of Khamenei, killed in the February strike, and of schoolgirls he said were killed at Minab, alongside images of their graves, and said the nuclear weapon is in Israel but the inspectors are in Iran. Iranian officials called Trump's threats a sign of strategic desperation. The Iran Human Rights roster of 4,200+ named protest dead, including 420 women and 281 under eighteen, carries alongside and is not merged. Rights thread carries: HRW and the Boroumand Center ≥59 arbitrary executions March 18-end August; Iran HRM 23 executions August 23-26. Economy unchanged and untouched by New York: rial past 2,000,000 and −44% in six months, official 12-month average inflation 69.9% against household inflation near 89%, unemployment 9.1%, average monthly salary ~$125 against ~$450 basic spending, 32 medicine categories short, loadings −85%. IAEA UNSC referral (23-3) and the September 9 Cairo safeguards modalities agreement carry; the Panel of Experts mandate lapses September 26-27. HRANA 3,636+; Foundation ~3,468; MOH ~3,559 / 27,400+; est. 6,000+.",
    other:
      "Six days of silence broke with claims, not confirmations: Houthi media reported a Saudi airstrike at Mocha killing six including two children, and a strike on a northern Yemeni prison killing nine detainees. Per §3.1 both are carried as Houthi claims and held outside the cumulative pending corroboration, on the al-Hazm precedent. Riyadh published no confirmation, no denial, and no answer to the September 19 capital strike for a seventh day. Displacement revised upward twice: the UN now puts it above 130,000 against the 112,000 the series carried, and forecasts more than 230,000 in the coming months, with IOM stocks near depletion. The 121-strike figure remains a Houthi claim dated September 8 and is carried as prior context. Energy: the East-West pipeline has restarted with several pumping stations still under repair; Yanbu loadings stay depressed; the shortfall is routed through Hormuz rather than replaced; regional flows averaged 17.1 mb/d over ten days and CENTCOM reports 1bn+ barrels moved by Gulf partners. Sohar STS ~60 mb carries. Lebanon (~4,300+/12,200+), Gulf (33+/~103+ Saudi; Kuwait 10/115), Iraq (148+/402+), maritime (~19 damaged / 7 abandoned / 2 captured / ~18 seafarers) and Mocha/coast (11+/32+) carry.",
  },
};

export default data;
