import type { BriefData } from '@/lib/brief-data';

const data: BriefData = {
  escalation: {
    direction: 'escalating',
    risk7d: 'extreme',
    spillover: 'critical',
    rationale: {
      direction:
        "Direction holds escalating on Day 190 as the kinetic ladder stayed paused a third day but the war's center of gravity moved to the narrative front. Vice President JD Vance declined to call the conflict a war — 'I wouldn't call this a war' — and pronounced himself 'extremely skeptical' of Iran's charge that the September 1 strike hit a wedding, dismissing Iranian state media, even as a New York Times visual analysis and an independent weapons expert concluded the wedding was struck by a US-released bomb. Per §3.5.3 read the day as an information-war escalation on top of a plateau, not a turn: the campaign is openly continuing, CENTCOM claimed fresh hits including two ships, Iran's IRIB vowed 'crushing and devastating blows,' oil firmed to six-week highs near $96, and Trump's standing warning that Iran would be 'hit much harder' if it retaliated was not withdrawn. Nothing on Day 190 reversed the return to force; the administration instead worked to reframe it.",
      risk7d:
        "Seven-day risk holds extreme. The mine-laying / strike / retaliation cycle is paused a third day, not closed, and the near-term tails stay loaded: a laden-tanker loss in a mined and contested strait, a lost escort convoy, a US casualty from an unintercepted salvo, a strike on a Gulf host, or a named major-Chinese-bank designation could each fire inside the week, and oil at a six-week high sits closer to the >$100 trigger on a drained stock base. The narrative front adds its own tail — the administration's simultaneous denial of the wedding strike and refusal of the 'war' label, set against independent forensic corroboration, keeps the legitimacy cost live and hands Tehran, Beijing and Moscow a running counter-narrative. Crisis Group reads Iran's escalation as a bid to keep its control of the strait from slipping as Washington's throughput claims gain ground — a dynamic that has repeatedly resolved into more fire.",
      spillover:
        "Spillover holds critical. No new theater opened on Day 190, which is why it did not worsen outright, but the map is unchanged and wide: Iranian soil under a continuing campaign, both maritime chokepoints, the Gulf host states directly targeted across the recent cycle, the Israel-Gaza and Israel-Lebanon seams, an open Houthi front now bearing on the Yanbu pipeline workaround, and a formalized economic front wired to the September 24 US-China summit. Per §3.5.5 the reach still outran the damage — Gulf and Jordanian interceptors held across the retaliation with no verified new fatality — but the target set spanning four-plus Arab states and the drawdown of global oil stocks are the standing signals, and Lloyd's List still calls the shipping picture 'peak disruption' even at higher raw transit counts.",
    },
  },
  events: [
    {
      id: 1,
      direction: 'pivotal',
      importance: 'pivotal',
      source: 'CBS News / Time / CNN / Democracy Now / The New York Times (via AOL)',
      event:
        "The war's center of gravity moved to the narrative front: Vice President JD Vance, at a White House briefing, declined to call the conflict a war — 'I wouldn't call this a war,' arguing active combat operations ended months ago — and said he was 'extremely skeptical' of Iran's allegation that the September 1 strike hit a wedding, dismissing Iranian state media as a poor 'scribe' of the conflict; a New York Times visual analysis and an independent weapons expert concluded the wedding was struck by a bomb released by US forces, and the Times reported Vance had been the most skeptical voice in Trump's inner circle before the strikes.",
      summary:
        "Per §3.5.3 the administration is now contesting both the war-crime charge and the 'war' label itself — an official-claim-versus-independent-forensics gap that is itself the signal, with the forensic record cutting against the denial.",
      impact:
        "The coalition-cohesion and political-will clocks move: downgrading the conflict to not-a-war manages the domestic, budgetary and war-powers exposure of an open-ended campaign, but independent corroboration of the wedding strike keeps the legitimacy cost live and feeds the China-Russia counter-narrative.",
    },
    {
      id: 2,
      direction: 'escalating',
      importance: 'high',
      source: 'USNI News / Lloyd’s List Intelligence / International Crisis Group / JMIC',
      event:
        "The US and Iran traded strikes and competing throughput narratives: a CENTCOM video claimed hits on Iranian targets including two unidentified ships while Iran's IRIB vowed 'crushing and devastating blows'; beneath the messaging the numbers gap widened — Treasury's Bessent claimed ten million barrels a day through Hormuz, fifteen to seventeen million on Tuesday, against the International Crisis Group's estimate of roughly five to seven million barrels a day of crude in August, and CENTCOM's Adm. Brad Cooper said the mines were cleared even as the Joint Maritime Information Center kept warning mariners of drifting mines.",
      summary:
        "Per §3.5.5 quantify the gap: independent tracking showed single-digit transits in each direction while US NCAGS data averaged over twenty a day, and about six vessels crossed Wednesday against eleven Tuesday and a ten-day average near thirteen — a strait running on dark, state-subsidised shuttle runs, not a reopening.",
      impact:
        "The energy-infrastructure and negotiation-capacity clocks move: Lloyd's List calls it 'peak disruption' even at higher raw counts, and Crisis Group reads Iran's escalation as a bid to keep its control of the strait — Tehran's main leverage — from slipping as Washington's throughput narrative gains ground.",
    },
    {
      id: 3,
      direction: 'escalating',
      importance: 'high',
      source: 'Trading Economics / Vantage Markets / Lloyd’s List Intelligence',
      event:
        "Oil firmed to six-week highs on the renewed Hormuz clash: Brent settled near $95.23 on Thursday and hovered around $96 at the top of the range, up from the low $90s near $92 a day earlier, with analysts citing Iran's overnight claims of strikes on US bases and Israel's signal that it was prepared to return to fighting; the Lloyd's List webinar warned that months of reduced transits have drawn down global stocks, leaving a stretched refining system with little slack against Ukrainian strikes on Russian refineries.",
      summary:
        "Per §3.5.5 the move is a re-pricing of the war the market had sold down — a roughly three-to-four-dollar lift toward $96 on a drained stock base, not a spike, but the rupture tail is visibly re-loaded.",
      impact:
        "The energy vector's rupture tail stays loaded and closer to the trigger: a laden-tanker loss, a lost escort convoy, or a named major-Chinese-bank designation would send Brent past $100 in a session, with the dual-closure $150-200 tail one sinking away.",
    },
    {
      id: 4,
      direction: 'mixed',
      importance: 'medium',
      source: 'CFR / Al Jazeera / CNBC',
      event:
        "The standing architecture ran on beneath the narrative war: the major-Chinese-bank blow stayed pinned behind Xi Jinping's September 24 White House visit, the CFR judging Beijing holds 'the upper hand'; Gaza held deadlocked, with the US-led Board of Peace insisting no Israeli withdrawal will occur before Hamas disarms while Hamas holds it will not act until Israel withdraws, and more than 1,200 Palestinians killed since the October 2025 ceasefire, at least 36 of them since the disarmament deal; the IAEA-Iran inspection modalities stayed a technical step short of verified access.",
      summary:
        "Per §3.5.6 the standing priors hold: the deferred China blow pinned to a fixed date, the Gaza sequencing deadlock, the unverified nuclear file, and China's role as the plan's hinge all persist unresolved.",
      impact:
        "The connected fronts neither eased nor were bound by the pause; the war widens on the water, in the sanctions arena, and in the legitimacy contest even on a day without a confirmed new strike wave.",
    },
  ],
  casualties: {
    us: {
      cumulative:
        'KIA: 17 confirmed · WIA: 432 (AP/CENTCOM combat series; ~96% returned to duty). DoD DCAS all-cause series holds 18 killed · 687 wounded.',
      delta:
        "+0 confirmed on the AP/CENTCOM combat series into Day 190 — a third day with no verified new US combat casualty even as the campaign and the information war continued. Iran's earlier claim of American service members killed stays denied by two US officials and uncounted; the DoD DCAS all-cause tally holds 18 killed / 687 wounded, still not a confirmed hostile combat loss, so Trump's 'per ship' rule is not triggered. The blockade holds at roughly eighty-six vessels rerouted, three disabled, two boarded; the escort convoy (~8-9 mb/d) runs amid live fire with the USS George Washington on station.",
      status:
        "The headline holds at 17 KIA / 432 WIA on the AP/CENTCOM combat series against the wider DoD DCAS all-cause tally of 18 killed / 687 wounded since February 28. Per §3.5.3 keep the combat figure and flag DCAS; the 18th DCAS death is unconfirmed as hostile and does not, on its own, trigger Trump's 'bridge or power plant per ship' rule. Day 190 added neither a claim nor a count on the US side — a third quiet day for US casualties — but the exposure is unchanged: the escort convoy (~660 million barrels and ~1,300 vessels since May, moving ~8-9 mb/d) runs amid live fire, CENTCOM's blockade holds at roughly eighty-six vessels rerouted, and Vance's 'I wouldn't call this a war' framing sits against a campaign that is still firing. Trump's standing 'hit much harder' warning keeps a single unintercepted salvo one event away from the reprisal rule. The $67 billion supplemental and the 50-48 Senate war-powers rebuke stay unresolved in recess ahead of the November midterms, and the not-a-war framing is itself a move in that political contest.",
    },
    israel: {
      cumulative: 'KIA: 56 (Iran-front 47 + Lebanon-front 9) · WIA: 8,652+',
      delta:
        "+0 on the Iran front; no new Israeli fatalities or wounded there. Israel stayed offstage on the US-Iran narrative fight while signalling it was prepared to return to fighting if needed, and its Gaza campaign held deadlocked and lethal — a connected theater, not folded into the war cumulative; strikes since the October 2025 ceasefire more than 1,200, at least 36 of them since the disarmament deal.",
      status:
        "Israeli casualties hold at 56 KIA / 8,652+ WIA on the Iran front; no new Iran-front toll on Day 190. Israel indicated it was prepared to re-enter the fighting if necessary but stayed offstage on the US-Iran narrative contest, while its own fronts stayed hot: the US-led Board of Peace insists no Israeli withdrawal from Gaza will occur before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap — the disarm-first / withdraw-first sequencing unresolved, with more than 1,200 Palestinians killed since the October 2025 ceasefire and at least 36 since the disarmament deal, a connected theater the series does not fold into the war cumulative. In Lebanon Israel kept striking Hezbollah and Hamas 'targets,' the threatened reprisal unexecuted, and UNIFIL's Khardali-Litani handover to the Lebanese Army's 7th Brigade carries. Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold — Israel acts on its own clock, outside the US-Iran framework.",
    },
    iran: {
      cumulative:
        'Foundation of Martyrs ~3,468 KIA · HRANA 3,636+ documented (1,221 mil / 1,701 civ / 714 unclassified) · MOH ~3,559 killed / 27,400+ wounded · US-Israeli est. 6,000+ · 3.2M displaced',
      delta:
        "The contested wedding-strike claim gained independent forensic support: a New York Times visual analysis and a weapons expert concluded the September 1 Kuhestak wedding was struck by a US-released bomb, even as Vice President Vance called himself 'extremely skeptical' of the Iranian account. The Iranian toll — up to five killed, reported to include children aged four and sixteen, and more than sixty-eight wounded — carries per §3.1 dual-sourcing: the strike is now corroborated but the casualty figure remains an Iranian-source count, held pending independent verification and not folded into the MOH headline; September 1 military casualties (sixteen minelayers, IRGC coastal sites) remain unreleased.",
      status:
        "The official Iranian war toll carries pending an update. The day's movement was on the contested civilian figure: a New York Times visual analysis and an independent weapons expert concluded the September 1 Kuhestak wedding was struck by a bomb released by US forces — corroborating the strike itself — while Vice President Vance pronounced himself 'extremely skeptical' of Iran's account and dismissed Iranian state media. Per §3.1 dual-sourcing the strike is now independently supported, but the toll of up to five killed (reported to include children aged four and sixteen) and more than sixty-eight wounded remains an Iranian-source count, held pending independent verification of the numbers and not folded into the MOH aggregate; September 1 military casualties (sixteen minelayers, IRGC sites across Bandar Abbas, Chabahar, Qeshm, Konarak and Sirik) remain unreleased. Cumulative HRANA stands at 3,636+ with its understatement caveat, Foundation of Martyrs ~3,468, MOH ~3,559 / 27,400+, and US and Israeli estimates run to 6,000+. Per §3.1 a separate and worsening rights thread is kept out of the war cumulative: UN High Commissioner Volker Türk tallied at least 56 executed since March 19, 27 tied to the January protests, 100+ at risk. The IAEA-Iran modalities stay a technical step, not verified access, with Iran's 'only after a deal' framing intact; the ~440.9 kg of 60% HEU plus ~184.1 kg of 20% stays unverified and likely at Isfahan, ISIS flagging enough for up to ten weapons if further enriched.",
    },
    other: {
      cumulative:
        "Lebanon source-split: Health Ministry ~4,265 / 12,190+ vs Wikipedia 3,371 / 10,129 · Iraq 148+ KIA / 402+ WIA · Gulf 33+ KIA / 85+ WIA (Kuwait 10 killed / 115 injured; Saudi Arabia 11 civilians injured, Aug 7) · Yemen (Mokha) 11+ killed / 32+ wounded · Bab al-Mandeb (Tihamah, Aug 12) at least 6 killed / 10 wounded per Yemen government (Houthis unconfirmed) · Hormuz-crisis maritime toll ~19 ships damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing",
      delta:
        "The spillover ledger held critical without a confirmed new death: the Gulf-host target set stayed wide but unfired-on in the past day, Gulf and Jordanian air defenses having held across the recent retaliation with no verified fatality. Hormuz transits read about six vessels Wednesday against eleven Tuesday (ten-day average near thirteen); non-Iranian traffic rose some 60% week-on-week yet Lloyd's List still calls it 'peak disruption'; the Houthi maritime blockade of Saudi-linked shipping now bears on the Yanbu pipeline workaround; the standing maritime, Lebanon and Bab al-Mandeb tolls carry.",
      status:
        "The 'other' ledger held critical in target set without a confirmed new death. The Gulf-host set stayed wide — Jordan, Bahrain, Kuwait and Iraq across the recent cycle — but the interceptors held and Day 190 added no verified fatality. Per §3.5.3 the standing Houthi Saudi-warship claim, the UAE ballistic-missile threat, and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz commercial transit read about six vessels Wednesday against eleven Tuesday and a ten-day average near thirteen, with independent tracking in single digits against US NCAGS data averaging over twenty a day; non-Iranian traffic rose roughly 60% week-on-week yet Lloyd's List still calls the picture 'peak disruption,' and the Houthi blockade of Saudi-linked ships now threatens the Yanbu pipeline reroute. War-risk premiums hold 3-10% of hull value and the Iran-Oman corridor stays clouded by fire. In Lebanon the Aug 15 strike that killed at least eleven including three children (Health Ministry cumulative ~4,265 / 12,190+, the Wikipedia series 3,371 / 10,129 lagging) holds as an unfulfilled Hezbollah-Israel threat exchange as UNIFIL's Khardali-Litani handover carries. The Bab al-Mandeb Tihamah toll (Aug 12) holds at least six killed and ten wounded per Yemen's government. The maritime toll holds ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
    },
  },
  exec:
    "Day 190 held the kinetic pause a third day but the war's center of gravity moved to the narrative front. Vice President JD Vance declined to call the conflict a war — 'I wouldn't call this a war,' saying active combat ended months ago — and pronounced himself 'extremely skeptical' of Iran's charge that the September 1 strike hit a wedding, dismissing Iranian state media; a New York Times visual analysis and an independent weapons expert concluded the wedding was struck by a US-released bomb, and the Times reported Vance had been the most skeptical voice in Trump's inner circle (CBS News, Time, CNN, NYT). Per §3.1 the strike is now independently corroborated while the toll — up to five killed, reportedly including children aged four and sixteen, and 68+ wounded — remains an Iranian-source count, not folded into the MOH aggregate. Beneath the messaging the throughput gap widened: Bessent's claim of 10-17 million barrels a day through Hormuz against the International Crisis Group's ~5-7 million a day of crude in August, and Adm. Cooper's 'mines cleared' against JMIC drifting-mine warnings (USNI, Lloyd's List, Crisis Group). Oil firmed to six-week highs, Brent near $95.23 and around $96 at the top, up from the low $90s near $92 (Trading Economics, Vantage). The economic architecture ran on — the major-Chinese-bank blow pinned behind Xi's September 24 visit, Gaza deadlocked (CFR, Al Jazeera). Direction holds escalating; seven-day risk extreme; spillover critical; the thirty-day ceasefire probability holds at 3.",
  implications: [
    {
      title: "The war over narrative — the administration disputes both the atrocity and the word 'war'",
      body:
        "With the guns quiet a third day, the contest ran on messaging, and Washington fought on two fronts at once. Vice President Vance told a White House briefing he was 'extremely skeptical' of Iran's charge that the September 1 strike hit a wedding, dismissing Iranian state media as a poor 'scribe,' and — in the same appearances — declined to call the conflict a war at all, arguing active combat operations ended months ago (CBS News, Time, CNN). Per §3.5.3 hold both claims against the independent record: a New York Times visual analysis and a weapons expert concluded the wedding was struck by a bomb released by US forces, and the Times reported Vance had been the most skeptical internal voice before the strikes — so the forensic evidence cuts against the denial while the 'not a war' framing sits over a campaign that is still firing. Under the multi-clock framework the political-will and coalition-cohesion clocks are the movers: downgrading the conflict manages the war-powers, budget and midterm exposure of an open-ended fight, but corroboration of the strike keeps the legitimacy cost live and hands Beijing and Moscow more to work with. Analytical judgment: when a principal contests both the facts of an atrocity and the name of the conflict, the gap between claim and record is the intelligence — and here the record is moving against the claim.",
    },
    {
      title: "Claim-versus-reality at the strait — throughput as a second theater of the information war",
      body:
        "The narrative war extended to the water, where the numbers themselves are contested. Treasury Secretary Bessent has touted ten million barrels a day through Hormuz, fifteen to seventeen million on Tuesday; the International Crisis Group put August crude at roughly five to seven million barrels a day, and CENTCOM's Adm. Cooper said the mines were cleared even as the Joint Maritime Information Center kept warning of drifting mines (USNI, Lloyd's List, Crisis Group). Per §3.5.5 quantify the gap: independent tracking showed single-digit transits in each direction while US NCAGS data averaged over twenty a day, about six vessels crossed Wednesday against eleven Tuesday and a ten-day mean near thirteen, and non-Iranian traffic rose some 60% week-on-week even as Lloyd's List called the picture 'peak disruption' run on dark, state-subsidised shuttle runs. Crisis Group reads Iran's renewed strikes as a bid to keep control of the strait — its main leverage — from slipping as Washington's throughput claims gain ground, the same pattern that has resolved into fire for six months. Analytical judgment: both capitals are now managing perceptions of the strait as hard as the strait itself, and the throughput a mined waterway can sustain under a blackout regime, on a drawn-down global stock base, is the fact that will out — most likely through price.",
    },
    {
      title: "Taiwan: the buffered month runs down as oil firms and the financial clock nears its date",
      body:
        "Per §3.5.10 no Iran-front development aimed at Taipei landed on Day 190, but the exposure sharpened as the physical and financial clocks converged. The physical one: September — the month Taiwan said in May it had gas cover 'through' — is now being drawn down with Brent at a six-week high near $96, Hormuz transits opaque and in the single-to-low-double digits, and the corridor clouded by fire (Energy Connects, Vantage). The financial one nears its date: the major-Chinese-bank sanction that would rupture the oil-for-money channel is still pinned behind Xi Jinping's September 24 White House visit (CFR), so the same late-September window that ends Taiwan's gas buffer also decides whether Washington fires its economic D-Day. Per §3.5.5 the arithmetic is unchanged and unforgiving: 95-99% import dependence, roughly a third of Taiwan's LNG through Hormuz with a large Qatari share, about eleven days of gas cover against some 120 of oil (CSIS). Analytical judgment: Taipei's early hedge toward US and Australian LNG and roughly 60% US crude was the right call, but a buffer is a countdown, not a solution — and with oil firming and the strait thinning as the buffer expires in the same fortnight the bank decision comes due, only supply that does not pass Hormuz closes the gap.",
    },
  ],
  casualtyNotes: {
    us:
      "Headline holds 17 KIA / 432 WIA (AP/CENTCOM combat series). DoD DCAS holds 18 killed / 687 wounded all-cause — a wider scope, not a confirmed new combat death; per §3.5.3 keep the combat series and flag DCAS. Day 190 was a third quiet day for US casualties: no verified US combat loss even as the campaign and information war continued; Iran's earlier claim of American service members killed stays denied and uncounted. CENTCOM's blockade holds at ~86 vessels rerouted, three disabled, two boarded; the escort convoy (~660M+ barrels / ~1,300 vessels since May, ~8-9 mb/d) runs amid live fire with the USS George Washington on station. Vance's 'I wouldn't call this a war' framing sits against a still-firing campaign; the $67B supplemental and 50-48 rebuke stay unresolved in recess ahead of the November midterms.",
    israel:
      "Iran-front casualties hold at 56 KIA / 8,652+ WIA; no new Iran-front toll. Israel signalled it was prepared to return to fighting if needed but stayed offstage on the US-Iran narrative contest, while its Gaza campaign held deadlocked and lethal — the Board of Peace insists no Israeli withdrawal before Hamas disarms, Hamas holds it will not act until Israel withdraws, and Israel has not confirmed it accepts the roadmap (a connected theater, not folded into the war cumulative; more than 1,200 killed since the October 2025 ceasefire, at least 36 since the disarmament deal). Per §3.5.6 the Lebanon-gap and Israeli-independence priors hold.",
    iran:
      "Official MOH war toll carries pending an update. The day's movement was independent corroboration of the strike: a New York Times visual analysis and a weapons expert concluded the Sep 1 Kuhestak wedding was struck by a US-released bomb, even as Vance called himself 'extremely skeptical' of Iran's account. Per §3.1 dual-sourcing the strike is now supported but the toll — up to five killed, reportedly including children aged four and sixteen, 68+ wounded — remains an Iranian-source count, held pending verification of the numbers and not folded into the MOH aggregate; Sep 1 military casualties remain unreleased. HRANA 3,636+; Foundation ~3,468; MOH ~3,559 / 27,400+; est. 6,000+. The execution wave carries out of the war toll (UN's Türk: 56 since Mar 19, 100+ at risk). Iran's claims of US service members killed and eight MQ-9s destroyed stay logged, not counted (§3.5.3). The IAEA-Iran modalities stay a technical step, not verified access; ~440.9 kg 60% + ~184.1 kg 20% HEU likely at Isfahan.",
    other:
      "The spillover ledger held critical without a confirmed new death: the Gulf-host target set stayed wide but unfired-on in the past day, Gulf and Jordanian interceptors having held across the recent retaliation with no verified fatality. Per §3.5.3 the Houthi Saudi-warship claim, the UAE-missile threat and Iran's eight-MQ-9 and downed-MQ-9 claims stay logged, not counted. Hormuz transits read ~6 Wednesday against 11 Tuesday (ten-day avg ~13), independent single-digit vs US NCAGS 20+/day; non-Iranian traffic +60% week-on-week yet 'peak disruption'; the Houthi blockade now threatens the Yanbu pipeline reroute; war-risk premiums 3-10% of hull; the Iran-Oman corridor stays clouded by fire. Lebanon's Aug 15 eleven-death strike (Health Ministry ~4,265 / 12,190+, Wikipedia 3,371 / 10,129 lags) holds as an unfulfilled threat exchange; Bab al-Mandeb Tihamah (Aug 12) holds at least 6 killed / 10 wounded. Maritime toll ~19 damaged / 7 abandoned / 2 captured / ~18 seafarers killed or missing; Mokha shut, ~1,300 idled; Kuwait 10/115; Iraq 148+/402+; Saudi 11 injured (Aug 7).",
  },
};

export default data;
